CREATE PROCEDURE dbo.CleanUp_SSAS_Monitoring
AS BEGIN

SET NOCOUNT ON;

BEGIN TRY
BEGIN TRAN

DECLARE @RETENTIONDAYS INT = (SELECT CAST(ParamValue AS INT) FROM [dbo].[SSAS_MonitoringParameters] WHERE [ParamName] = 'StatExtract_RetentionDays');

DELETE FROM [dbo].[SSAS_Monitoring]
WHERE DATEADD(DAY, @RETENTIONDAYS, [TimeStampUtc]) < GETDATE()

COMMIT TRAN
END TRY

BEGIN CATCH

IF @@TRANCOUNT > 0
	ROLLBACK TRAN

DECLARE @ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
SELECT @ERRORMESSAGE = ERROR_MESSAGE() + ' LINE ' + CAST(ERROR_LINE() AS NVARCHAR(5)), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();

RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);

END CATCH

END